development:
    dialect: postgres
    datasource: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=${PGSSLMODE}
    dir: migrations
    table: migrations

spec:
    dialect: postgres
    datasource: postgres://${PSQL_USER}:${PSQL_PASS}@${PSQL_HOST}:${PSQL_PORT}/${PSQL_DBNAME}?sslmode=${PSQL_SSLMODE}
    dir: migrations
    table: migrations