-- +migrate Up

ALTER TABLE users ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE roles ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE tenants ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE topics ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE sub_topics ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE posts ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE answers ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE votes ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE comments ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE tags ALTER COLUMN created_at SET NOT NULL;