-- +migrate Down
DROP TABLE IF EXISTS user_claims;
DROP TABLE IF EXISTS role_claims;
DROP TABLE IF EXISTS post_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS sub_topics;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS claims;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS tenants;
