// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateTopicResponse create topic response
//
// swagger:model createTopicResponse
type CreateTopicResponse struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this create topic response
func (m *CreateTopicResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create topic response based on context it is used
func (m *CreateTopicResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateTopicResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateTopicResponse) UnmarshalBinary(b []byte) error {
	var res CreateTopicResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
