// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateSubTopicRequest create sub topic request
//
// swagger:model createSubTopicRequest
type CreateSubTopicRequest struct {

	// name
	// Required: true
	Name *string `json:"name"`

	// topic
	// Required: true
	Topic *CreateSubTopicRequestTopic `json:"topic"`
}

// Validate validates this create sub topic request
func (m *CreateSubTopicRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTopic(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateSubTopicRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *CreateSubTopicRequest) validateTopic(formats strfmt.Registry) error {

	if err := validate.Required("topic", "body", m.Topic); err != nil {
		return err
	}

	if m.Topic != nil {
		if err := m.Topic.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("topic")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("topic")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this create sub topic request based on the context it is used
func (m *CreateSubTopicRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTopic(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateSubTopicRequest) contextValidateTopic(ctx context.Context, formats strfmt.Registry) error {

	if m.Topic != nil {

		if err := m.Topic.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("topic")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("topic")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateSubTopicRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSubTopicRequest) UnmarshalBinary(b []byte) error {
	var res CreateSubTopicRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CreateSubTopicRequestTopic create sub topic request topic
//
// swagger:model CreateSubTopicRequestTopic
type CreateSubTopicRequestTopic struct {

	// id
	// Required: true
	ID *int64 `json:"id"`
}

// Validate validates this create sub topic request topic
func (m *CreateSubTopicRequestTopic) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateSubTopicRequestTopic) validateID(formats strfmt.Registry) error {

	if err := validate.Required("topic"+"."+"id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create sub topic request topic based on context it is used
func (m *CreateSubTopicRequestTopic) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateSubTopicRequestTopic) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSubTopicRequestTopic) UnmarshalBinary(b []byte) error {
	var res CreateSubTopicRequestTopic
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
