// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// DeleteUserRequest delete user request
//
// swagger:model deleteUserRequest
type DeleteUserRequest int64

// Validate validates this delete user request
func (m DeleteUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete user request based on context it is used
func (m DeleteUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
