// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteUserResponse delete user response
//
// swagger:model deleteUserResponse
type DeleteUserResponse struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this delete user response
func (m *DeleteUserResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete user response based on context it is used
func (m *DeleteUserResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteUserResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteUserResponse) UnmarshalBinary(b []byte) error {
	var res DeleteUserResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
