// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteTenantResponse delete tenant response
//
// swagger:model deleteTenantResponse
type DeleteTenantResponse struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this delete tenant response
func (m *DeleteTenantResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete tenant response based on context it is used
func (m *DeleteTenantResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteTenantResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteTenantResponse) UnmarshalBinary(b []byte) error {
	var res DeleteTenantResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
