// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteSubTopicResponse delete sub topic response
//
// swagger:model deleteSubTopicResponse
type DeleteSubTopicResponse struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this delete sub topic response
func (m *DeleteSubTopicResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete sub topic response based on context it is used
func (m *DeleteSubTopicResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteSubTopicResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteSubTopicResponse) UnmarshalBinary(b []byte) error {
	var res DeleteSubTopicResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
