// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateClaimResponse update claim response
//
// swagger:model updateClaimResponse
type UpdateClaimResponse struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this update claim response
func (m *UpdateClaimResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update claim response based on context it is used
func (m *UpdateClaimResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateClaimResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateClaimResponse) UnmarshalBinary(b []byte) error {
	var res UpdateClaimResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
