// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateTopicRequest update topic request
//
// swagger:model updateTopicRequest
type UpdateTopicRequest struct {

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this update topic request
func (m *UpdateTopicRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update topic request based on context it is used
func (m *UpdateTopicRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateTopicRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateTopicRequest) UnmarshalBinary(b []byte) error {
	var res UpdateTopicRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
