// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateRoleResponse update role response
//
// swagger:model updateRoleResponse
type UpdateRoleResponse struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this update role response
func (m *UpdateRoleResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update role response based on context it is used
func (m *UpdateRoleResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateRoleResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateRoleResponse) UnmarshalBinary(b []byte) error {
	var res UpdateRoleResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
