// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateUserResponse update user response
//
// swagger:model updateUserResponse
type UpdateUserResponse struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this update user response
func (m *UpdateUserResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update user response based on context it is used
func (m *UpdateUserResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateUserResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateUserResponse) UnmarshalBinary(b []byte) error {
	var res UpdateUserResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
