// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateTopicResponse update topic response
//
// swagger:model updateTopicResponse
type UpdateTopicResponse struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this update topic response
func (m *UpdateTopicResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update topic response based on context it is used
func (m *UpdateTopicResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateTopicResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateTopicResponse) UnmarshalBinary(b []byte) error {
	var res UpdateTopicResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
