basePath: /api/v1
definitions:
  cuhara_qua_go_internal_auth_application_query.LoginRequest:
    properties:
      email:
        type: string
    type: object
  cuhara_qua_go_internal_auth_application_query.LoginResponse:
    properties:
      token:
        type: string
    type: object
  cuhara_qua_go_internal_roles_application_command.CreateRoleRequest:
    properties:
      name:
        example: ADMIN
        maxLength: 100
        minLength: 2
        type: string
    required:
    - name
    type: object
  cuhara_qua_go_internal_roles_application_command.CreateRoleResponse:
    properties:
      id:
        example: 1
        type: integer
    type: object
  cuhara_qua_go_internal_tennants_application_command.CreateTennantRequest:
    properties:
      name:
        example: KOÇ HOLDİNG AŞ
        maxLength: 100
        minLength: 2
        type: string
    required:
    - name
    type: object
  cuhara_qua_go_internal_tennants_application_command.CreateTennantResponse:
    properties:
      id:
        type: integer
    type: object
  cuhara_qua_go_internal_users_application_command.CreateUserRequest:
    properties:
      email:
        example: john@example.com
        type: string
      name:
        example: John Doe
        type: string
      role_id:
        example: 1
        type: integer
      tenant_id:
        example: 1
        type: integer
      vsc_account:
        example: john_doe
        type: string
    required:
    - email
    - name
    - role_id
    - tenant_id
    type: object
  cuhara_qua_go_internal_users_application_command.CreateUserResponse:
    properties:
      id:
        example: 1
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  title: Cuhara QUA API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/cuhara_qua_go_internal_auth_application_query.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cuhara_qua_go_internal_auth_application_query.LoginResponse'
      summary: Login user with email
      tags:
      - auth
  /roles:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/cuhara_qua_go_internal_roles_application_command.CreateRoleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/cuhara_qua_go_internal_roles_application_command.CreateRoleResponse'
      summary: Create a new role
      tags:
      - roles
  /tennants:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: tennant
        required: true
        schema:
          $ref: '#/definitions/cuhara_qua_go_internal_tennants_application_command.CreateTennantRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/cuhara_qua_go_internal_tennants_application_command.CreateTennantResponse'
      summary: Create a new Tennant
      tags:
      - Tennant
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/cuhara_qua_go_internal_users_application_command.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/cuhara_qua_go_internal_users_application_command.CreateUserResponse'
      summary: Create a new user
      tags:
      - users
swagger: "2.0"
