swagger: "2.0"
info:
  title: HTTP Error Models
  version: 0.1.0
  description: Only HTTP error models retained
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/auth/login:
    post:
      tags:
        - auth
      summary: Login
      description: Login to the system
      parameters:
        - name: login
          in: body
          required: true
          schema:
            $ref: "#/definitions/loginRequest"
      responses:
        200:
          description: Login successful
          schema:
            $ref: "#/definitions/loginResponse"

  /api/v1/auth/register:
    post:
      tags:
        - auth
      summary: Register
      description: Register a new user
      parameters:
        - name: register
          in: body
          required: true
          schema:
            $ref: "#/definitions/registerRequest"
      responses:
        200:
          description: Register successful
          schema:
            $ref: "#/definitions/registerResponse"

  /api/v1/users:
    get:
      tags:
        - users
      summary: Get users
      description: Get all users
      responses:
        200:
          description: Users fetched successfully
          schema:
            $ref: "#/definitions/userResponse"

    put:
      tags:
        - users
      summary: Update user
      description: Update a user
      parameters:
        - name: updateUser
          in: body
          required: true
          schema:
            $ref: "#/definitions/updateUserRequest"
      responses:
        200:
          description: User updated successfully
          schema:
            $ref: "#/definitions/updateUserResponse"

  /api/v1/users/{id}:
    delete:
      tags:
        - users
      summary: Delete user
      description: Delete a user
      parameters:
        - $ref: "#/parameters/IDPathParam"
      responses:
        200:
          description: User deleted successfully
          schema:
            $ref: "#/definitions/deleteUserResponse"

  /api/v1/tenants:
    get:
      tags:
        - tenant
      summary: Get tenants
      description: Get all tenants
      responses:
        200:
          description: tenants fetched successfully
          schema:
            $ref: "#/definitions/tenantResponse"

    post:
      tags:
        - tenant
      summary: Create tenant
      description: Create a new tenant
      parameters:
        - name: createTenant
          in: body
          required: true
          schema:
            $ref: "#/definitions/createTenantRequest"
      responses:
        200:
          description: Tenant created successfully
          schema:
            $ref: "#/definitions/createTenantResponse"

  /api/v1/tenants/{id}:
    patch:
      tags:
        - tenant
      summary: Update tenant
      description: Update a tenant
      parameters:
        - $ref: "#/parameters/IDPathParam"
        - name: updateTenant
          in: body
          required: true
          schema:
            $ref: "#/definitions/updateTenantRequest"
      responses:
        200:
          description: Tenant updated successfully
          schema:
            $ref: "#/definitions/updateTenantResponse"

    delete:
      tags:
        - tenant
      summary: Delete tenant
      description: Delete a tenant
      parameters:
        - $ref: "#/parameters/IDPathParam"
      responses:
        200:
          description: Tenant deleted successfully
          schema:
            $ref: "#/definitions/deleteTenantResponse"

  /api/v1/roles:
    get:
      tags:
        - role
      summary: Get roles
      description: Get all roles
      responses:
        200:
          description: Roles fetched successfully
          schema:
            $ref: "#/definitions/roleResponse"

    post:
      tags:
        - role
      summary: Create role
      description: Create a new role
      parameters:
        - name: createRole
          in: body
          required: true
          schema:
            $ref: "#/definitions/createRoleRequest"
      responses:
        200:
          description: Role created successfully
          schema:
            $ref: "#/definitions/createRoleResponse"

  /api/v1/roles/{id}:
    patch:
      tags:
        - role
      summary: Update role
      description: Update a role
      parameters:
        - $ref: "#/parameters/IDPathParam"
        - name: updateRole
          in: body
          required: true
          schema:
            $ref: "#/definitions/updateRoleRequest"
      responses:
        200:
          description: Role updated successfully
          schema:
            $ref: "#/definitions/updateRoleResponse"

    delete:
      tags:
        - role
      summary: Delete role
      description: Delete a role
      parameters:
        - $ref: "#/parameters/IDPathParam"
      responses:
        200:
          description: Role deleted successfully
          schema:
            $ref: "#/definitions/deleteRoleResponse"
  
  /api/v1/topics:
    get:
      tags:
        - topic
      summary: Get topics
      description: Get all topics
      responses:
        200:
          description: Topics fetched successfully
          schema:
            $ref: "#/definitions/topicResponse"
            
    post:
      tags:
        - topic
      summary: Create topic
      description: Create a new topic
      parameters:
        - name: createTopic
          in: body
          required: true
          schema:
            $ref: "#/definitions/createTopicRequest"
      responses:
        200:
          description: Topic created successfully
          schema:
            $ref: "#/definitions/createTopicResponse"
  
  /api/v1/topics/{id}:
    patch:
      tags:
        - topic
      summary: Update topic
      description: Update a topic
      parameters:
        - $ref: "#/parameters/IDPathParam"
        - name: updateTopic
          in: body
          required: true
          schema:
            $ref: "#/definitions/updateTopicRequest"
      responses:
        200:
          description: Topic updated successfully
          schema:
            $ref: "#/definitions/updateTopicResponse"
  
    delete:
      tags:
        - topic
      summary: Delete topic
      description: Delete a topic
      parameters:
        - $ref: "#/parameters/IDPathParam"
      responses:
        200:
          description: Topic deleted successfully
          schema:
            $ref: "#/definitions/deleteTopicResponse"
  
  /api/v1/topics/{id}/sub-topics:
    get:
      tags:
        - topic
      summary: Get sub topics
      description: Get all sub topics
      parameters:
        - $ref: "#/parameters/IDPathParam"
      responses:
        200:
          description: Sub topics fetched successfully
          schema:
            $ref: "#/definitions/subTopicResponse"
  
    post:
      tags:
        - topic
      summary: Create sub topic
      description: Create a new sub topic
      parameters:
        - $ref: "#/parameters/IDPathParam"
        - name: createSubTopic
          in: body
          required: true
          schema:
            $ref: "#/definitions/createSubTopicRequest"
      responses:
        200:
          description: Sub topic created successfully
          schema:
            $ref: "#/definitions/createSubTopicResponse"
  
  /api/v1/topics/{id}/sub-topics/{subId}:
    patch:
      tags:
        - topic
      summary: Update sub topic
      description: Update a sub topic
      parameters:
        - $ref: "#/parameters/IDPathParam"
        - $ref: "#/parameters/SubIDPathParam"
        - name: updateSubTopic
          in: body
          required: true
          schema:
            $ref: "#/definitions/updateSubTopicRequest"
      responses:
        200:
          description: Sub topic updated successfully
          schema:
            $ref: "#/definitions/updateSubTopicResponse"
  
    delete:
      tags:
        - topic
      summary: Delete sub topic
      description: Delete a sub topic
      parameters:
        - $ref: "#/parameters/IDPathParam"
        - $ref: "#/parameters/SubIDPathParam"
      responses:
        200:
          description: Sub topic deleted successfully
          schema:
            $ref: "#/definitions/deleteSubTopicResponse"

  /api/v1/claims:
    get:
      tags:
        - claim
      summary: Get claims
      description: Get all claims
      responses:
        200:
          description: Claims fetched successfully
          schema:
            $ref: "#/definitions/claimResponse"
            
    post:
      tags:
        - claim
      summary: Create claim
      description: Create a new claim
      parameters:
        - name: createClaim
          in: body
          required: true
          schema:
            $ref: "#/definitions/createClaimRequest"
      responses:
        200:
          description: Claim created successfully
          schema:
            $ref: "#/definitions/createClaimResponse"
  
  /api/v1/claims/{id}:
    patch:
      tags:
        - claim
      summary: Update claim
      description: Update a claim
      parameters:
        - $ref: "#/parameters/IDPathParam"
        - name: updateClaim
          in: body
          required: true
          schema:
            $ref: "#/definitions/updateClaimRequest"
      responses:
        200:
          description: Claim updated successfully
          schema:
            $ref: "#/definitions/updateClaimResponse"
  
    delete:
      tags:
        - claim
      summary: Delete claim
      description: Delete a claim
      parameters:
        - $ref: "#/parameters/IDPathParam"
      responses:
        200:
          description: Claim deleted successfully
          schema:
            $ref: "#/definitions/deleteClaimResponse"

parameters:
  SubIDPathParam:
    name: subId
    in: path
    description: Sub topic ID
    required: true
    type: integer

  IDPathParam:
    name: id
    in: path
    description: User ID
    required: true
    type: integer

definitions:
  deleteClaimResponse:
    type: object
    properties:
      id:
        type: integer

  updateClaimResponse:
    type: object
    properties:
      id:
        type: integer

  updateClaimRequest:
    type: object
    properties:
      name:
        type: string
      description:
        type: string

  createClaimResponse:
    type: object
    properties:
      id:
        type: integer

  createClaimRequest:
    type: object
    required:
      - name
      - description
    properties:
      name:
        type: string
      description:
        type: string

  claimResponse:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      description:
        type: string

  deleteSubTopicResponse:
    type: object
    properties:
      id:
        type: integer

  updateSubTopicResponse:
    type: object
    properties:
      id:
        type: integer

  updateSubTopicRequest:
    type: object
    properties:
      name:
        type: string
      topic:
        type: object
        properties:
          id:
            type: integer

  createSubTopicResponse:
    type: object
    properties:
      id:
        type: integer

  createSubTopicRequest:
    type: object
    required:
      - name
      - topic
    properties:
      name:
        type: string
      topic:
        type: object
        required:
          - id
        properties:
          id:
            type: integer
  
  subTopicResponse:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      topic:
        type: object
        $ref: "#/definitions/topicResponse"
        
  deleteTopicResponse:
    type: object
    properties:
      id:
        type: integer

  updateTopicResponse:
    type: object
    properties:
      id:
        type: integer

  updateTopicRequest:
    type: object
    properties:
      name:
        type: string

  createTopicResponse:
    type: object
    properties:
      id:
        type: integer

  createTopicRequest:
    type: object
    required:
      - name
    properties:
      name:
        type: string

  topicResponse:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string

  deleteRoleResponse:
    type: object
    properties:
      id:
        type: integer


  updateRoleResponse:
    type: object
    properties:
      id:
        type: integer


  updateRoleRequest:
    type: object
    properties:
      name:
        type: string

  createRoleResponse:
    type: object
    properties:
      id:
        type: integer
        
  createRoleRequest:
    type: object
    required:
      - name
      - tenant
    properties:
      name:
        type: string
      tenant:
        type: object
        required:
          - id
        properties:
          id:
            type: integer

  roleResponse:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      tenant:
        $ref: "#/definitions/tenantResponse"

  deleteTenantResponse:
    type: object
    properties:
      id:
        type: integer

  updateTenantRequest:
    type: object
    properties:
      name:
        type: string

  updateTenantResponse:
    type: object
    properties:
      id:
        type: integer

  createTenantRequest:
    type: object
    required:
      - name
    properties:
      name:
        type: string

  createTenantResponse:
    type: object
    properties:
      id:
        type: integer

  tenantResponse:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string

  deleteUserRequest:
    type: integer
  deleteUserResponse:
    type: object
    properties:
      id:
        type: integer

  updateUserRequest:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
      vscAccount:
        type: string
      role:
        type: object
        required:
          - id
        properties:
          id:
            type: integer

  updateUserResponse:
    type: object
    properties:
      id:
        type: integer

  userResponse:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
      vscAccount:
        type: string

  loginRequest:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
      password:
        type: string

  loginResponse:
    type: object
    properties:
      token:
        type: string

  registerRequest:
    type: object
    required:
      - name
      - email
      - password
      - vscAccount
      - roleID
      - tenantID
    properties:
      name:
        type: string
      email:
        type: string
      password:
        type: string
      vscAccount:
        type: string
      roleID:
        type: integer

      tenantID:
        type: integer


  registerResponse:
    type: object
    properties:
      id:
        type: integer


  httpValidationErrorDetail:
    type: object
    required:
      - key
      - in
      - error
    properties:
      error:
        description: Error describing field validation failure
        type: string
      in:
        description: Indicates how the invalid field was provided
        type: string
      key:
        description: Key of field failing validation
        type: string

  publicHttpError:
    type: object
    required:
      - status
      - type
      - title
    properties:
      detail:
        description: More detailed, human-readable, optional explanation of the error
        type: string
        example: User is lacking permission to access this resource
      status:
        description: HTTP status code returned for the error
        type: integer
        format: int64
        maximum: 599
        minimum: 100
        x-go-name: Code
        example: 403
      title:
        description: Short, human-readable description of the error
        type: string
        example: Forbidden
      type:
        description: Type of error returned, should be used for client-side error handling
        type: string
        example: generic

  publicHttpValidationError:
    type: object
    required:
      - validationErrors
    allOf:
      - $ref: "#/definitions/publicHttpError"
    properties:
      validationErrors:
        description: List of errors received while validating payload against schema
        type: array
        items:
          $ref: "#/definitions/httpValidationErrorDetail"
